spring:
  jpa:
      show-sql: false
      database: POSTGRESQL
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            default_schema: stockmarketdata
            jdbc:
               time_zone: UTC
               lob:
                  non_contextual_creation: true
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: welcome1a
      platform: postgres
# Liquibase configuration
  liquibase:
      enabled: true
      change-log: classpath:/databaseScripts/DatabaseScript.xml
      liquibase-schema: public
      default-schema: stockmarketdata
server: 
   port: 5555